server: 
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database-1.cx0iygoqyfre.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: g9T4ow$2*E7,72BZ;MCxiOE9qBOz!WK$
  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect